name: serialporttoolgui # you probably want to 'snapcraft register <name>'
version: '0.0.1.20210925' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A Cross-platform serial test tool. # 79 char long summary
description: |
  A simple Cross-platform serial test tool, created by Joker2770< https://github.com/Joker2770/SerialPortToolGUI >.

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  serialporttoolgui:
    command: SerialPortToolGUI
    extensions: [gnome-3-28]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - serial-port
      
layout:
  /usr/local/bin/SerialPortToolGUI.ui:
    bind-file: $SNAP/usr/local/bin/SerialPortToolGUI.ui

parts:
  serialporttoolgui:
    # See 'snapcraft plugins'
    plugin: cmake
    source: https://github.com/Joker2770/SerialPortToolGUI.git
    source-type: git
    source-branch: main
    source-depth: 1
    # source: ./
    build-packages:
      - build-essential
      - gcc
      - make
      - cmake
      - libgtk-3-dev
  
    stage-packages:
      - libgtk-3-0

